### ISSUE TITLE
get doesn't return synchronously 

### ISSUE THREAD

**Issue by wanderer** [rvagg/memdown#30]
it would be nice if `get` could return the result directly.

**Comment by wanderer** [comment]
PR #31

**Comment by calvinmetcalf** [comment]
so this is an in memory adapter for levelup, which is all async, if you need an async in memory datastore you might be better off using [what we use](https://www.npmjs.com/package/functional-red-black-tree) directly

**Comment by wanderer** [comment]
thanks @calvinmetcalf that looks like what i need

**Comment by ccorcos** [comment]
Hey there, just wanted to mention that I made something a solution for sync callbacks:

https://github.com/Level/mem/pull/50
